apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrm-demo-fe-deployment
  namespace: metafi-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vrm-demo-fe
  template:
    metadata:
      labels:
        app: vrm-demo-fe
    spec:
      containers:
      - name: vrm-demo-fe-container
        image: metafi/vrm-demo:0.1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"