apiVersion: v1
kind: Service
metadata:
  name: vrm-demo-service
  namespace: metafi-system
spec:
  type: NodePort
  selector:
    app: vrm-demo-fe
  ports:
  - protocol: TCP
    port: 80          
    targetPort: 80    
    nodePort: 30012   # Expose the service on this port  